name: blood_link
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  google_sign_in: ^6.2.1
  google_nav_bar: ^5.0.6
  carousel_slider: ^4.2.1
  vertical_card_pager: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/
  fonts:
    - family: Helvetica
      fonts:
        - asset: lib/Fonts/Helvetica-Font/Helvetica.ttf
